apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: soaxkuort-go 
  janus-idp.io/tekton: soaxkuort-go
  backstage.io/kubernetes-id: soaxkuort-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: soaxkuort-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  